export const uiText = {
  zh: {
    appName: "MornStudio",
    appSubtitle: "一句话驱动多媒体生成、编辑与AI内容检测",
    guest: "访客",
    freePlan: "免费版",
    basicPlan: "基础版",
    proPlan: "专业版",
    enterprisePlan: "企业版",
    activeSubscription: "订阅中",
    expiresAt: "到期",
    login: "登录",
    loginButton: "登录",
    signup: "注册",
    reset: "找回密码",
    account: "账户",
    subscribeButton: "订阅",
    upgradeTip: "开通订阅，解锁更多用量与高级模型",
    modalClose: "关闭",
    authWelcome: "账户中心",
    authHint: "真实账户状态，已接入后端鉴权",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    verificationCode: "验证码",
    sendCode: "发送验证码",
    showPassword: "显示",
    hidePassword: "隐藏",
    signIn: "登录账户",
    createAccount: "创建账户",
    resetPassword: "重置密码",
    forgotPassword: "忘记密码？",
    backToLogin: "返回登录",
    noAccount: "还没有账号？",
    haveAccount: "已有账号？",
    logout: "退出登录",
    loggedInAs: "当前登录",
    subscription: "订阅方案",
    billingMonthly: "月付",
    billingAnnual: "年付",
    saveThirty: "年付省30%",
    subscribeNow: "立即订阅",
    subscribeHint: "请先登录后完成订阅",
    paymentMethod: "支付方式",
    quota: "额度总览",
    dailyExternal: "每日外部模型",
    monthlyDocument: "每月文档",
    monthlyImage: "每月图片",
    monthlyVideo: "每月视频/音频",
    addonImage: "加油包图片",
    addonVideo: "加油包视频/音频",
    operationsTitle: "AI 工作台",
    dashboardTitle: "账户与订阅",
    promptPlaceholderText: "输入一句话，例如：把图片背景换成海边，并导出为PDF说明文档",
    promptPlaceholderImage: "输入一句话生成或编辑图片，例如：替换人物、去背景、修复画质",
    promptPlaceholderAudio: "输入一句话生成或编辑音频，例如：降噪、配音、风格迁移",
    promptPlaceholderVideo: "输入一句话生成或编辑视频，例如：换背景、加字幕、转风格",
    promptPlaceholderDetection: "输入检测指令，例如：检测这张图片是否为AI生成或经过AI编辑",
    temperature: "温度参数",
    maxTokens: "最大输出长度",
    generating: "生成中...",
    generate: "立即生成",
    recentTasks: "最近任务",
    noTasks: "暂无任务记录",
    languageSwitchToEn: "切换到英文",
    languageSwitchToZh: "切换到中文",
    switchToLight: "切换到亮色模式",
    switchToDark: "切换到暗色模式",
  },
  en: {
    appName: "MornStudio",
    appSubtitle:
      "One-line creation, editing and AI-origin detection for multimedia",
    guest: "Guest",
    freePlan: "Free",
    basicPlan: "Basic",
    proPlan: "Pro",
    enterprisePlan: "Enterprise",
    activeSubscription: "Active subscription",
    expiresAt: "Expires",
    login: "Sign in",
    loginButton: "Login",
    signup: "Sign up",
    reset: "Recover",
    account: "Account",
    subscribeButton: "Pro",
    upgradeTip: "Upgrade to unlock more usage and advanced models",
    modalClose: "Close",
    authWelcome: "Account Center",
    authHint: "Live account status with backend authentication",
    name: "Name",
    email: "Email",
    password: "Password",
    verificationCode: "Code",
    sendCode: "Send code",
    showPassword: "Show",
    hidePassword: "Hide",
    signIn: "Sign in",
    createAccount: "Create account",
    resetPassword: "Reset password",
    forgotPassword: "Forgot password?",
    backToLogin: "Back to sign in",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    logout: "Sign out",
    loggedInAs: "Signed in as",
    subscription: "Subscription",
    billingMonthly: "Monthly",
    billingAnnual: "Annual",
    saveThirty: "Save 30% annual",
    subscribeNow: "Subscribe now",
    subscribeHint: "Please sign in before subscribing",
    paymentMethod: "Payment",
    quota: "Quota Overview",
    dailyExternal: "Daily external models",
    monthlyDocument: "Monthly docs",
    monthlyImage: "Monthly images",
    monthlyVideo: "Monthly video/audio",
    addonImage: "Add-on images",
    addonVideo: "Add-on video/audio",
    operationsTitle: "AI Operations",
    dashboardTitle: "Account & Billing",
    promptPlaceholderText:
      "Try: Replace the image background with a beach and export a PDF brief",
    promptPlaceholderImage:
      "Try: Replace person, remove background, upscale quality",
    promptPlaceholderAudio:
      "Try: Denoise, voice clone, style transfer for audio",
    promptPlaceholderVideo:
      "Try: Replace background, add subtitles, video style transfer",
    promptPlaceholderDetection:
      "Try: Check whether this image is AI-generated or AI-edited",
    temperature: "Temperature",
    maxTokens: "Max tokens",
    generating: "Generating...",
    generate: "Run",
    recentTasks: "Recent tasks",
    noTasks: "No tasks yet",
    languageSwitchToEn: "Switch to English",
    languageSwitchToZh: "Switch to Chinese",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
  },
} as const;

export type UILanguage = keyof typeof uiText;

export function getUIText(language: string) {
  return language === "zh" ? uiText.zh : uiText.en;
}
