import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '../../../lib/supabase'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { prompt, type, settings, userId } = body

    // Validate input
    if (!prompt || !type) {
      return NextResponse.json(
        { error: 'Missing required fields: prompt and type' },
        { status: 400 }
      )
    }

    // Check user credits (if userId provided)
    if (userId) {
      const { data: user, error: userError } = await supabase
        .from('users')
        .select('credits')
        .eq('id', userId)
        .single()

      if (userError || !user) {
        return NextResponse.json(
          { error: 'User not found' },
          { status: 404 }
        )
      }

      if (user.credits <= 0) {
        return NextResponse.json(
          { error: 'Insufficient credits' },
          { status: 402 }
        )
      }
    }

    // Mock generation delay
    await new Promise(resolve => setTimeout(resolve, 1500))

    // Mock response based on content type
    let result = ''
    switch (type) {
      case 'text':
        result = `Generated text content: "${prompt}"\n\nThis is a sample generated text based on your prompt. In a real implementation, this would be generated by an AI model like GPT-4 or similar. The content would be tailored to your specific requirements and the tone/style settings you've selected.`
        break
      case 'image':
        result = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MTIiIGhlaWdodD0iNTEyIiBmaWxsPSIjRjNGNEY2Ii8+Cjx0ZXh0IHg9IjI1NiIgeT0iMjU2IiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMjQiIGZpbGw9IiM5Q0EzQUYiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5HZW5lcmF0ZWQgSW1hZ2U8L3RleHQ+Cjwvc3ZnPgo='
        break
      case 'audio':
        result = 'data:audio/wav;base64,UklGRnoGAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQoGAACBhYqFbF1fdJivrJBhNjVgodDbq2EcBj+a2/LDciUFLIHO8tiJNwgZaLvt559NEAxQp+PwtmMcBjiR1/LMeSwFJHfH8N2QQAoUXrTp66hVFApGn+DyvmwhBSuBzvLZiTYIG2m98OScTgwOUarm7blmGgU7k9n1unEiBC13yO/eizEIHWq+8+OWT'
        break
      case 'video':
        result = 'data:video/mp4;base64,AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAAGxtZGF0AAACmwYF//+p3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE0OCByMjkyMSA3ZDBlYjQxIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAxNSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcWw9MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTYgbG9va2FoZWFkX3RocmVhZHM9MSBzbGljZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz0zIGJfcHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWlnaHRwPTIga2V5aW50PTI1MCBrZXlpbnRfbWluPTEwIHNjZW5lY3V0PTQwIGludHJhX3JlZnJlc2g9MCByY19sb29rYWhlYWQ9NDAgcmM9Y3JmIG1idHJlZT0xIGNyZj0yMy4wIHFjb21wPTAuMCA='
        break
      default:
        return NextResponse.json(
          { error: 'Unsupported content type' },
          { status: 400 }
        )
    }

    // Store generation in database
    try {
      const { data: generation, error: insertError } = await supabase
        .from('generations')
        .insert({
          user_id: userId || null,
          type,
          prompt,
          result,
          status: 'completed',
          config: settings || {}
        })
        .select()
        .single()

      if (insertError) {
        console.error('Database insert error:', insertError)
        // If database tables don't exist or connection fails, return a mock response
        if (insertError.code === '42P01' || insertError.message?.includes('fetch failed')) {
          const mockResponse = {
            id: `mock-${Date.now()}`,
            type,
            content: result,
            timestamp: new Date().toISOString(),
            settings: settings || {},
            prompt
          }
          return NextResponse.json(mockResponse)
        }
        return NextResponse.json(
          { error: 'Failed to save generation' },
          { status: 500 }
        )
      }

      const response = {
        id: generation.id,
        type: generation.type,
        content: generation.result,
        timestamp: generation.created_at,
        settings: generation.config,
        prompt: generation.prompt
      }

      return NextResponse.json(response)
    } catch (error) {
      console.error('Database connection error:', error)
      // Return mock response if database is not available
      const mockResponse = {
        id: `mock-${Date.now()}`,
        type,
        content: result,
        timestamp: new Date().toISOString(),
        settings: settings || {},
        prompt
      }
      return NextResponse.json(mockResponse)
    }

    // Deduct credits if user is authenticated
    if (userId) {
      try {
        const { error: creditError } = await supabase
          .from('users')
          .update({ credits: supabase.rpc('decrement_credits', { user_id: userId }) })
          .eq('id', userId)

        if (creditError) {
          console.error('Credit deduction error:', creditError)
        }
      } catch (error) {
        console.error('Credit deduction failed:', error)
      }
    }
  } catch (error) {
    console.error('Generation error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
} 